hide_download: true
hide_download_original: null
leftnav:
- identifier: e212b9aa-7e3e-e1d7-8bbe-4f8fcfb4626a
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: bfed90c3-6b3f-38d3-0731-2d3542da5c3e
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: e1e8ff3c-2dba-3ffb-8d6a-ce0e85bd54da
  name: Readings
  pageRef: /pages/readings
  weight: 30
- identifier: 8bace91d-9f2d-6d98-8abf-c4b35aafbe65
  name: Lecture Notes
  pageRef: /pages/lecture-notes
  weight: 40
- identifier: 4b1af640-a5f8-cd18-9d24-9653c2760d65
  name: Projects
  pageRef: /pages/projects
  weight: 50
